# Generated by Django 5.2.1 on 2025-05-21 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.PositiveIntegerField()),
                ('phoneNumber', models.CharField(max_length=15)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental.workertype')),
            ],
        ),
    ]
